# Generated by Django 2.1.7 on 2019-02-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Last',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_file', models.TextField(default='df.png', max_length=1000)),
            ],
        ),
    ]
